# Generated by Django 5.2.16 on 2026-08-13 03:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_owned_channels(apps, schema_editor):
    OwnedChannel = apps.get_model("sources", "OwnedChannel")
    rows = [
        (
            "WEEKLYONSTOCK_OFFICIAL",
            "证券市场周刊官网",
            "OFFICIAL_WEBSITE",
            {"domains": ["weeklyonstock.com"]},
            "官网域名规则已确认。",
        ),
        (
            "TOUTIAO",
            "今日头条",
            "PLATFORM_ACCOUNT",
            {"platform_domains": ["toutiao.com"], "account_names": ["证券市场周刊"]},
            "需由搜索结果账号元数据确认。",
        ),
        (
            "SOHU",
            "搜狐",
            "PLATFORM_ACCOUNT",
            {"platform_domains": ["sohu.com"], "account_names": ["证券市场周刊"]},
            "需由搜索结果账号元数据确认。",
        ),
        (
            "XUEQIU",
            "雪球",
            "PLATFORM_ACCOUNT",
            {"platform_domains": ["xueqiu.com"], "account_names": ["证券市场周刊"]},
            "需由搜索结果账号元数据确认。",
        ),
        (
            "BAIJIA",
            "百家",
            "PLATFORM_ACCOUNT",
            {"platform_domains": ["baidu.com"], "account_names": ["证券市场周刊"]},
            "需由搜索结果账号元数据确认。",
        ),
        (
            "EASTMONEY",
            "东方财富",
            "PLATFORM_ACCOUNT",
            {"platform_domains": ["eastmoney.com"], "account_names": ["证券市场周刊"]},
            "需由搜索结果账号元数据确认。",
        ),
        (
            "NETEASE",
            "网易",
            "PLATFORM_ACCOUNT",
            {"platform_domains": ["163.com"], "account_names": ["证券市场周刊"]},
            "需由搜索结果账号元数据确认。",
        ),
        (
            "WEIBO",
            "微博",
            "PLATFORM_ACCOUNT",
            {"platform_domains": ["weibo.com"], "account_names": ["证券市场周刊"]},
            "需由搜索结果账号元数据确认。",
        ),
        (
            "JD_FINANCE",
            "京东金融",
            "PLATFORM_ACCOUNT",
            {"platform_domains": ["jd.com"], "account_names": ["证券市场周刊"]},
            "需由搜索结果账号元数据确认。",
        ),
        (
            "WEEKLYONSTOCK_MARKET",
            "证券市场周刊-市场号",
            "WECHAT_ACCOUNT",
            {"account_names": ["证券市场周刊-市场号"]},
            "公众号账号标识待接入搜索元数据后确认。",
        ),
        (
            "HONGKAN_INVESTOR",
            "红刊投服平台",
            "WECHAT_ACCOUNT",
            {"account_names": ["红刊投服平台"]},
            "公众号账号标识待接入搜索元数据后确认。",
        ),
    ]
    for code, name, channel_type, match_rules, notes in rows:
        OwnedChannel.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "channel_type": channel_type,
                "is_active": True,
                "match_rules": match_rules,
                "notes": notes,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0003_searchruncandidate"),
        ("sources", "0003_articleingestconflict"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnedChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="来源代码只能包含大写英文字母、数字和下划线。",
                                regex="^[A-Z0-9_]+$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("OFFICIAL_WEBSITE", "官方网站"),
                            ("PLATFORM_ACCOUNT", "平台账号"),
                            ("WECHAT_ACCOUNT", "公众号"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("match_rules", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sources_owned_channel",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="searchrun",
            name="broad_candidate_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchrun",
            name="exact_candidate_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchrun",
            name="merged_candidate_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchrun",
            name="owned_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchrun",
            name="repost_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchrun",
            name="review_required_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchruncandidate",
            name="classification_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="searchruncandidate",
            name="classified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchruncandidate",
            name="content_relation",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="searchruncandidate",
            name="search_phases",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="searchruncandidate",
            name="owned_channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="search_candidates",
                to="sources.ownedchannel",
            ),
        ),
        migrations.RunPython(seed_owned_channels, migrations.RunPython.noop),
    ]
