# Generated by Django 5.2.16 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sources", "0004_ownedchannel_searchrun_broad_candidate_count_and_more")]

    operations = [
        migrations.AlterField(
            model_name="searchruncandidate",
            name="disposition",
            field=models.CharField(
                choices=[
                    ("PENDING", "待比对"),
                    ("EXCLUDED_SOURCE", "原创来源链接"),
                    ("EXCLUDED_ORIGINAL", "原创文章链接"),
                    ("EXCLUDED_TOO_EARLY", "发布时间早于原创"),
                    ("EXCLUDED_MANUAL", "人工排除"),
                    ("NOT_MATCHED", "未匹配"),
                    ("MATCHED", "已匹配转载"),
                ],
                default="PENDING",
                max_length=32,
            ),
        )
    ]
