# Generated by Django 5.2.16 on 2026-08-13

from django.conf import settings
import django.core.validators
from django.db import migrations, models


def seed_configured_provider(apps, schema_editor):
    SearchProviderConfiguration = apps.get_model("sources", "SearchProviderConfiguration")
    provider = getattr(settings, "SEARCH_PROVIDER", "").strip().lower()
    names = {"tencent_wsa": "腾讯云联网搜索", "brave": "Brave Search API"}
    if provider in names:
        SearchProviderConfiguration.objects.get_or_create(
            code=provider,
            defaults={"name": names[provider], "enabled": True, "priority": 10},
        )


class Migration(migrations.Migration):
    dependencies = [("sources", "0005_alter_searchruncandidate_disposition")]

    operations = [
        migrations.CreateModel(
            name="SearchProviderConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="搜索来源代码只能包含小写英文字母、数字和下划线。",
                                regex="^[a-z0-9_]+$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(db_index=True, default=False)),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_failure_code", models.CharField(blank=True, max_length=64)),
                ("last_failure_message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "sources_search_provider_configuration", "ordering": ["priority", "code"]},
        ),
        migrations.RunPython(seed_configured_provider, migrations.RunPython.noop),
    ]
