# Generated by Django 5.2.16 on 2026-08-13

from django.db import migrations


def add_verified_bing_provider(apps, schema_editor):
    SearchProviderConfiguration = apps.get_model("sources", "SearchProviderConfiguration")
    SearchProviderConfiguration.objects.get_or_create(
        code="bing_html",
        defaults={"name": "Bing public result page", "enabled": True, "priority": 20},
    )


class Migration(migrations.Migration):
    dependencies = [("sources", "0007_searchruncandidate_provider_codes")]

    operations = [migrations.RunPython(add_verified_bing_provider, migrations.RunPython.noop)]
