# Generated by Django 5.2.16 on 2026-08-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0008_enable_verified_bing_html_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetedCrawlTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "待领取"), ("CLAIMED", "已领取"), ("CLOSED", "已关闭")],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("claim_token_hash", models.CharField(blank=True, default="", max_length=64)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("claim_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("next_available_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_completed_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, default="", max_length=64)),
                ("last_error_message", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_crawl_task",
                        to="articles.article",
                    ),
                ),
                (
                    "claimed_by_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_targeted_crawl_tasks",
                        to="sources.sourceingesttoken",
                    ),
                ),
                (
                    "last_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_crawl_tasks",
                        to="sources.searchrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targeted_crawl_tasks",
                        to="sources.source",
                    ),
                ),
            ],
            options={
                "db_table": "sources_targeted_crawl_task",
                "ordering": ["next_available_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="targetedcrawltask",
            index=models.Index(fields=["source", "status", "next_available_at"], name="sources_tar_source__cbb47e_idx"),
        ),
    ]
