# Generated by Django 5.2.16 on 2026-08-17

from django.db import migrations


def seed_other_owned_channel(apps, schema_editor):
    OwnedChannel = apps.get_model("sources", "OwnedChannel")
    OwnedChannel.objects.update_or_create(
        code="OTHER",
        defaults={
            "name": "其他",
            "channel_type": "PLATFORM_ACCOUNT",
            "is_active": True,
            "match_rules": {},
            "notes": "仅供人工归入阅读量；不配置自动匹配规则。",
        },
    )


def remove_other_owned_channel(apps, schema_editor):
    apps.get_model("sources", "OwnedChannel").objects.filter(code="OTHER").delete()


class Migration(migrations.Migration):
    dependencies = [("sources", "0009_targetedcrawltask")]

    operations = [migrations.RunPython(seed_other_owned_channel, remove_other_owned_channel)]
