# Generated by Django 5.2.16 on 2026-08-17 07:04

import django.core.validators
from django.db import migrations, models


def seed_automatic_repost_sites(apps, schema_editor):
    AutomaticRepostSite = apps.get_model("sources", "AutomaticRepostSite")
    rows = [
        ("TIANTIAN_ONLINE", "天天在线", ["116.com.cn"]),
        ("STOCKSTAR", "证券之星", ["stockstar.com"]),
        ("CNFOL", "中金在线", ["cnfol.com"]),
        ("EASTMONEY", "东方财富", ["finance.eastmoney.com"]),
        ("SINA_FINANCE", "新浪财经", ["finance.sina.com.cn"]),
        ("NETEASE", "网易", ["163.com"]),
        ("ZAKER", "ZAKER", ["myzaker.com", "zaker.cn"]),
        ("TONGDAXIN", "通达信", ["tdx.com.cn"]),
        ("DAZHUIHUI", "大智慧", ["gw.com.cn"]),
        ("TENCENT_SELF_SELECT", "腾讯自选股", ["gu.qq.com", "stockapp.finance.qq.com"]),
        ("TONGHUASHUN", "同花顺", ["10jqka.com.cn"]),
    ]
    for code, name, domains in rows:
        AutomaticRepostSite.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "domains": domains,
                "is_active": True,
                "notes": "搜索候选相似度达到系统候选阈值时自动归入外部转载。",
            },
        )


def unseed_automatic_repost_sites(apps, schema_editor):
    codes = [
        "TIANTIAN_ONLINE",
        "STOCKSTAR",
        "CNFOL",
        "EASTMONEY",
        "SINA_FINANCE",
        "NETEASE",
        "ZAKER",
        "TONGDAXIN",
        "DAZHUIHUI",
        "TENCENT_SELF_SELECT",
        "TONGHUASHUN",
    ]
    apps.get_model("sources", "AutomaticRepostSite").objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0010_seed_other_owned_channel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomaticRepostSite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="来源代码只能包含大写英文字母、数字和下划线。", regex="^[A-Z0-9_]+$"
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("domains", models.JSONField(default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sources_automatic_repost_site",
                "ordering": ["code"],
            },
        ),
        migrations.RunPython(seed_automatic_repost_sites, unseed_automatic_repost_sites),
    ]
