# Generated by Django 5.2.16 on 2026-08-17

from django.db import migrations


def configure_caifuhao_owned_channel(apps, schema_editor):
    OwnedChannel = apps.get_model("sources", "OwnedChannel")
    OwnedChannel.objects.filter(code="EASTMONEY").update(
        name="财富号",
        match_rules={"subdomains": ["caifuhao.eastmoney.com"]},
        notes="财富号子域名（caifuhao.eastmoney.com）直接归入自有渠道阅读量；东方财富财经新闻页不属于该规则。",
    )


def restore_eastmoney_owned_channel(apps, schema_editor):
    OwnedChannel = apps.get_model("sources", "OwnedChannel")
    OwnedChannel.objects.filter(code="EASTMONEY").update(
        name="东方财富",
        match_rules={"platform_domains": ["eastmoney.com"], "account_names": ["证券市场周刊"]},
        notes="需由搜索结果账号元数据确认。",
    )


class Migration(migrations.Migration):
    dependencies = [("sources", "0011_automaticrepostsite")]

    operations = [migrations.RunPython(configure_caifuhao_owned_channel, restore_eastmoney_owned_channel)]
