# Generated by Django 5.2.16 on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reposts", "0004_repostrecord_classification_reason_and_more"),
        ("sources", "0012_configure_caifuhao_owned_channel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingMetricObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reading_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "成功"), ("NOT_FOUND", "未查到"), ("ERROR", "失败")],
                        db_index=True,
                        default="SUCCESS",
                        max_length=16,
                    ),
                ),
                ("observed_at", models.DateTimeField(db_index=True)),
                ("error_message", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repost_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_metric_observations",
                        to="reposts.repostrecord",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reading_metric_observations",
                        to="sources.source",
                    ),
                ),
            ],
            options={
                "db_table": "sources_reading_metric_observation",
                "ordering": ["-observed_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="readingmetricobservation",
            index=models.Index(fields=["repost_record", "-observed_at"], name="sources_rea_repost__5c9b11_idx"),
        ),
        migrations.AddIndex(
            model_name="readingmetricobservation",
            index=models.Index(fields=["source", "-observed_at"], name="sources_rea_source__8e0fd3_idx"),
        ),
    ]
