# Generated by Django 5.2.16 on 2026-08-25 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0013_readingmetricobservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readingmetricobservation",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reading_metric_observations",
                to="sources.source",
            ),
        ),
    ]
