# Generated by Django 5.2.16 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0014_alter_readingmetricobservation_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetedcrawltask",
            name="first_scan_done",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="targetedcrawltask",
            name="first_scan_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
