# Generated by Django 5.2.3 on 2026-08-06 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待配置"),
                            ("TESTING", "测试中"),
                            ("ENABLED", "已启用"),
                            ("DISABLED", "已停用"),
                            ("BROKEN", "规则失效"),
                            ("ARCHIVED", "已归档"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "adapter_type",
                    models.CharField(
                        choices=[
                            ("PUBLIC_API", "公开接口"),
                            ("HTML_SEARCH", "HTML 搜索"),
                            ("PLAYWRIGHT", "浏览器采集"),
                            ("CHANNEL_SCAN", "栏目扫描"),
                            ("RSS", "RSS"),
                            ("SITEMAP", "Sitemap"),
                            ("CUSTOM", "专用适配器"),
                        ],
                        default="HTML_SEARCH",
                        max_length=30,
                    ),
                ),
                ("default_max_pages", models.PositiveSmallIntegerField(default=5)),
                ("default_max_results", models.PositiveSmallIntegerField(default=100)),
                ("request_interval_ms", models.PositiveIntegerField(default=2000)),
                ("timeout_seconds", models.PositiveSmallIntegerField(default=15)),
                ("retry_count", models.PositiveSmallIntegerField(default=2)),
                ("config_version", models.PositiveIntegerField(default=1)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("adapter_notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "platform_platform",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlatformDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=253, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="platforms.platform",
                    ),
                ),
            ],
            options={
                "db_table": "platform_domain",
            },
        ),
    ]
