# Generated by Django 5.2.16 on 2026-08-13 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reposts", "0003_global_repost_fields"),
        ("sources", "0004_ownedchannel_searchrun_broad_candidate_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repostrecord",
            name="classification_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="repostrecord",
            name="classified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repostrecord",
            name="content_relation",
            field=models.CharField(
                choices=[
                    ("REPOST", "外部转载"),
                    ("OWNED", "自有分发"),
                    ("REVIEW_REQUIRED", "待审核"),
                ],
                db_index=True,
                default="REPOST",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="repostrecord",
            name="owned_channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="discovered_records",
                to="sources.ownedchannel",
            ),
        ),
    ]
