# Generated by Django 5.2.16 on 2026-08-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_duplicate_protection"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="channel_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="channel_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="article",
            name="section_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="section_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
