<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { api, downloadApiFile } from "./api";

defineProps<{ canOperate: boolean }>();

type Tab = "detect" | "status" | "results" | "export";
type Article = {
  id: number; title: string; published_at: string | null; published_date: string; channel_code: string; channel_name: string; section_code: string; section_name: string;
  author: string; monitoring_status: string; monitor_started_at: string | null; monitor_until: string | null; last_searched_at: string | null; next_search_at: string | null;
  search_run_count: number; repost_site_count: number; repost_url_count: number;
};
type Option = { code: string; name: string };
type Summary = { article_count: number; repost_article_count: number; repost_site_count: number; repost_url_count: number };
type TrendPoint = { published_date: string; article_count: number; site_count: number; repost_url_count: number };
type Workspace = { as_of: string; results: Article[]; summary: Summary; monitoring_status_counts: Record<string, number>; trend: TrendPoint[]; channels: Option[]; sections: Option[]; pagination: { page: number; page_size: number; total: number } };
type Publication = { id: number; site_name: string; site_domain: string; canonical_url: string; normalized_url: string; result_title: string; content_relation: string; owned_channel_name: string | null; first_found_at: string | null; availability_status: string };
type SearchRun = { id: number; status: string; provider: string; exact_candidate_count: number; broad_candidate_count: number; merged_candidate_count: number; matched_count: number; repost_count: number; review_required_count: number; new_repost_count: number; error_code: string; error_message: string; created_at: string; completed_at: string | null };
type Candidate = { id: number; search_run_id: number; searched_at: string; title: string; site_name: string; site_domain: string; canonical_url: string; published_at: string | null; search_phases: string[]; disposition: string; similarity_score: string | null; content_relation: string; classification_reason: string };
type OwnedChannel = { id: number; code: string; name: string };
type ReviewAction = "CONFIRM_REPOST" | "CONFIRM_OWNED" | "EXCLUDE";

const tab = ref<Tab>((new URLSearchParams(location.search).get("tab") as Tab) || "detect");
const loading = ref(true); const submitting = ref(false); const exporting = ref(false); const error = ref("");
const rows = ref<Article[]>([]); const channels = ref<Option[]>([]); const sections = ref<Option[]>([]); const summary = ref<Summary>({ article_count: 0, repost_article_count: 0, repost_site_count: 0, repost_url_count: 0 }); const monitoringStatusCounts = ref<Record<string, number>>({ PENDING: 0, ACTIVE: 0, COMPLETED: 0, ERROR: 0 }); const trend = ref<TrendPoint[]>([]);
const page = ref(1); const pageSize = ref(20); const total = ref(0); const asOf = ref(""); const selected = ref<Article[]>([]);
const filters = ref({ range: "7", published_from: "", published_to: "", channel: "", section: "", monitoring_status: "", has_repost: "", site_domain: "", q: "" });
const detailOpen = ref(false); const detailLoading = ref(false); const detail = ref<{ article: Article; reposts: Publication[]; runs: SearchRun[]; candidates: Candidate[] } | null>(null); const ownedChannels = ref<OwnedChannel[]>([]);
const reviewDialogOpen = ref(false); const reviewingCandidate = ref<Candidate | null>(null); const reviewAction = ref<ReviewAction>("CONFIRM_REPOST"); const reviewReason = ref(""); const reviewOwnedChannelId = ref<number | null>(null); const reviewSubmitting = ref(false);
let pollTimer: number | undefined;

function shanghaiDate(value = new Date()): string { const parts = new Intl.DateTimeFormat("en-US", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(value); const field = (type: string): string => parts.find((part) => part.type === type)?.value || ""; return `${field("year")}-${field("month")}-${field("day")}`; }
function shanghaiDateDaysAgo(days: number): string { const now = new Date(); const shanghaiNow = new Date(`${shanghaiDate(now)}T12:00:00+08:00`); shanghaiNow.setDate(shanghaiNow.getDate() - days); return shanghaiDate(shanghaiNow); }
const presetStart = computed(() => { const days = Number(filters.value.range); return days ? shanghaiDateDaysAgo(days - 1) : ""; });
const effectiveFrom = computed(() => filters.value.range === "custom" ? filters.value.published_from : presetStart.value);
const query = computed(() => { const params = new URLSearchParams({ page: String(page.value), page_size: String(pageSize.value) }); const items: Record<string, string> = { published_from: effectiveFrom.value, published_to: filters.value.range === "custom" ? filters.value.published_to : shanghaiDate(), channel: filters.value.channel, section: filters.value.section, monitoring_status: filters.value.monitoring_status, has_repost: filters.value.has_repost, site_domain: filters.value.site_domain, q: filters.value.q }; Object.entries(items).forEach(([key, value]) => { if (value) params.set(key, value); }); return params; });
const svgPoints = computed(() => { if (!trend.value.length) return ""; const max = Math.max(1, ...trend.value.map((point) => point.repost_url_count)); return trend.value.map((point, index) => `${index * (680 / Math.max(1, trend.value.length - 1)) + 20},${150 - (point.repost_url_count / max) * 120}`).join(" "); });

function updateUrl(): void { const params = new URLSearchParams(location.search); params.set("tab", tab.value); history.replaceState(null, "", `${location.pathname}?${params.toString()}`); }
function statusLabel(value: string): string { return ({ PENDING: "待监测", ACTIVE: "监测中", COMPLETED: "已完成", ERROR: "异常" } as Record<string, string>)[value] || value; }
function relationLabel(value: string): string { return ({ REPOST: "外部转载", REVIEW_REQUIRED: "待复核" } as Record<string, string>)[value] || "候选待复核"; }
function rangeChanged(): void { if (filters.value.range !== "custom") { filters.value.published_from = ""; filters.value.published_to = ""; } page.value = 1; void load(); }
function resetFilters(): void { filters.value = { range: "7", published_from: "", published_to: "", channel: "", section: "", monitoring_status: "", has_repost: "", site_domain: "", q: "" }; page.value = 1; void load(); }

async function load(showLoading = true): Promise<void> {
  if (showLoading) loading.value = true; error.value = "";
  try { const data = await api<Workspace>(`/repost-monitor/results?${query.value.toString()}`); rows.value = data.results; channels.value = data.channels; sections.value = data.sections; summary.value = data.summary; monitoringStatusCounts.value = data.monitoring_status_counts; trend.value = data.trend; total.value = data.pagination.total; asOf.value = data.as_of; }
  catch (caught) { error.value = caught instanceof Error ? caught.message : "转载检测数据加载失败"; }
  finally { if (showLoading) loading.value = false; }
}
async function queueIds(ids: number[], selectionMode: "IDS" | "FILTER" = "IDS"): Promise<void> {
  submitting.value = true; error.value = "";
  try { const payload = selectionMode === "FILTER" ? { selection_mode: "FILTER", filters: Object.fromEntries(query.value.entries()) } : { selection_mode: "IDS", article_ids: ids }; const response = await api<{ queued_count: number }>("/global-search-runs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); ElMessage.success(`已提交 ${response.queued_count} 篇文章进行检测`); selected.value = []; await load(false); }
  catch (caught) { error.value = caught instanceof Error ? caught.message : "提交检测失败"; }
  finally { submitting.value = false; }
}
async function queueSelected(): Promise<void> { if (!selected.value.length) { ElMessage.warning("请先选择文章"); return; } await queueIds(selected.value.map((item) => item.id)); }
async function queueFilter(): Promise<void> { if (!total.value) return; try { await ElMessageBox.confirm(`即将按当前筛选范围发起检测，共 ${total.value} 篇文章。一次最多 500 篇。`, "确认全网转载检测", { type: "warning" }); await queueIds([], "FILTER"); } catch { /* user cancelled */ } }
async function openDetail(article: Article): Promise<void> { detailOpen.value = true; detailLoading.value = true; detail.value = null; try { const [data, reading] = await Promise.all([api<{ reposts: Publication[]; search_runs: SearchRun[]; candidates: Candidate[] }>(`/articles/${article.id}/discovered-publications?as_of=${encodeURIComponent(asOf.value)}`), api<{ channels: OwnedChannel[] }>("/reading-monitor/owned-publications")]); detail.value = { article, reposts: data.reposts, runs: data.search_runs, candidates: data.candidates }; ownedChannels.value = reading.channels; } catch (caught) { error.value = caught instanceof Error ? caught.message : "详情加载失败"; } finally { detailLoading.value = false; } }
function reviewDialogTitle(): string { return reviewAction.value === "CONFIRM_REPOST" ? "确认外部转载" : reviewAction.value === "CONFIRM_OWNED" ? "归入阅读量" : "排除候选"; }
function reviewCandidate(candidate: Candidate, action: ReviewAction): void { reviewingCandidate.value = candidate; reviewAction.value = action; reviewReason.value = ""; reviewOwnedChannelId.value = null; reviewDialogOpen.value = true; }
async function submitCandidateReview(): Promise<void> { const candidate = reviewingCandidate.value; const reason = reviewReason.value.trim(); if (!candidate) return; if (!reason) { ElMessage.warning("必须填写复核原因"); return; } if (reviewAction.value === "CONFIRM_OWNED" && !reviewOwnedChannelId.value) { ElMessage.warning("请选择自有渠道"); return; } reviewSubmitting.value = true; error.value = ""; try { await api(`/search-candidates/${candidate.id}/review`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: reviewAction.value, reason, ...(reviewAction.value === "CONFIRM_OWNED" ? { owned_channel_id: reviewOwnedChannelId.value } : {}) }) }); ElMessage.success(reviewAction.value === "CONFIRM_REPOST" ? "已确认外部转载" : reviewAction.value === "CONFIRM_OWNED" ? "已归入阅读量检测" : "候选已排除"); reviewDialogOpen.value = false; if (detail.value) await openDetail(detail.value.article); await load(false); } catch (caught) { error.value = caught instanceof Error ? caught.message : "复核提交失败"; } finally { reviewSubmitting.value = false; } }
async function exportExcel(): Promise<void> { exporting.value = true; try { await load(false); await downloadApiFile(`/repost-monitor/export.xlsx?${query.value.toString()}&as_of=${encodeURIComponent(asOf.value)}`); } catch (caught) { error.value = caught instanceof Error ? caught.message : "导出失败"; } finally { exporting.value = false; } }

watch(tab, updateUrl); watch([page, pageSize], () => void load());
onMounted(async () => { await load(); pollTimer = window.setInterval(() => void load(false), 5 * 60 * 1000); });
onBeforeUnmount(() => { if (pollTimer !== undefined) window.clearInterval(pollTimer); });
</script>

<template>
  <section class="monitoring-panel">
    <div class="heading"><div><h1>转载检测</h1><p>所有检测由后台搜索任务执行；列表刷新和导出只读取已保存数据。</p></div><el-button @click="load">刷新数据</el-button></div>
    <el-tabs v-model="tab" class="workspace-tabs"><el-tab-pane label="全网转载检测" name="detect" /><el-tab-pane label="监测状态" name="status" /><el-tab-pane label="查看监测结果" name="results" /><el-tab-pane label="导出 Excel" name="export" /></el-tabs>
    <el-alert v-if="error" :title="error" type="error" :closable="false" />
    <el-skeleton v-else-if="loading" :rows="8" animated />
    <template v-else>
      <section class="filters"><el-select v-model="filters.channel" clearable placeholder="全部栏目" @change="page=1; load()"><el-option v-for="item in channels" :key="item.code" :label="item.name" :value="item.code" /></el-select><el-select v-model="filters.section" clearable placeholder="全部子栏目" @change="page=1; load()"><el-option v-for="item in sections" :key="item.code" :label="item.name" :value="item.code" /></el-select><el-radio-group v-model="filters.range" @change="rangeChanged"><el-radio-button label="7">近7日</el-radio-button><el-radio-button label="15">近15日</el-radio-button><el-radio-button label="30">近30日</el-radio-button><el-radio-button label="custom">自定义</el-radio-button></el-radio-group><template v-if="filters.range === 'custom'"><el-date-picker v-model="filters.published_from" type="date" value-format="YYYY-MM-DD" placeholder="开始日期" /><el-date-picker v-model="filters.published_to" type="date" value-format="YYYY-MM-DD" placeholder="结束日期" /></template><el-select v-model="filters.monitoring_status" clearable placeholder="监测状态"><el-option label="待监测" value="PENDING" /><el-option label="监测中" value="ACTIVE" /><el-option label="已完成" value="COMPLETED" /><el-option label="异常" value="ERROR" /></el-select><el-select v-model="filters.has_repost" clearable placeholder="是否有转载"><el-option label="已发现转载" value="true" /><el-option label="尚无转载" value="false" /></el-select><el-input v-model="filters.site_domain" clearable placeholder="转载网站域名" class="title-filter" /><el-input v-model="filters.q" clearable placeholder="搜索文章标题" class="title-filter" /><el-button type="primary" @click="page=1; load()">查询</el-button><el-button @click="resetFilters">重置</el-button></section>
      <template v-if="tab === 'detect'"><div class="actions"><span>当前筛选共 {{ total }} 篇；已选择 {{ selected.length }} 篇</span><el-button type="primary" :disabled="!selected.length" :loading="submitting" @click="queueSelected">检测已选择文章</el-button><el-button :disabled="!total" :loading="submitting" @click="queueFilter">检测当前筛选范围</el-button></div><el-empty v-if="!rows.length" description="近7日暂无原创文章，可切换到近15日或调整筛选。" /><el-table v-else :data="rows" @selection-change="selected=$event"><el-table-column type="selection" width="52" /><el-table-column prop="published_at" label="发布时间" min-width="150" /><el-table-column label="栏目" min-width="130"><template #default="scope">{{ scope.row.channel_name || scope.row.section_name || '—' }}</template></el-table-column><el-table-column prop="title" label="标题" min-width="260" /><el-table-column prop="author" label="作者" width="110" /><el-table-column label="监测状态" width="110"><template #default="scope"><el-tag size="small">{{ statusLabel(scope.row.monitoring_status) }}</el-tag></template></el-table-column><el-table-column prop="repost_site_count" label="转载网站数" width="110" /><el-table-column prop="repost_url_count" label="转载链接数" width="110" /><el-table-column prop="last_searched_at" label="最近检测时间" min-width="170" /><el-table-column label="操作" width="150"><template #default="scope"><el-button link type="primary" :loading="submitting" @click="queueIds([scope.row.id])">立即检测</el-button><el-button link @click="openDetail(scope.row)">查看</el-button></template></el-table-column></el-table></template>
      <template v-else-if="tab === 'status'"><div class="status-summary"><el-card><b>监测中</b><strong>{{ monitoringStatusCounts.ACTIVE || 0 }}</strong></el-card><el-card><b>已完成</b><strong>{{ monitoringStatusCounts.COMPLETED || 0 }}</strong></el-card><el-card><b>异常</b><strong>{{ monitoringStatusCounts.ERROR || 0 }}</strong></el-card><el-card><b>待监测</b><strong>{{ monitoringStatusCounts.PENDING || 0 }}</strong></el-card></div><el-table :data="rows"><el-table-column prop="published_at" label="发布时间" min-width="150" /><el-table-column prop="title" label="标题" min-width="280" /><el-table-column prop="author" label="作者" /><el-table-column label="状态"><template #default="scope"><el-tag>{{ statusLabel(scope.row.monitoring_status) }}</el-tag></template></el-table-column><el-table-column prop="monitor_started_at" label="监测开始" min-width="160" /><el-table-column prop="monitor_until" label="监测截止" min-width="160" /><el-table-column prop="last_searched_at" label="最近检测" min-width="160" /><el-table-column prop="next_search_at" label="下次检测" min-width="160" /><el-table-column prop="search_run_count" label="搜索次数" /><el-table-column prop="repost_url_count" label="转载链接" /></el-table></template>
      <template v-else-if="tab === 'results'"><div class="summary"><span>原创文章 {{ summary.article_count }}</span><span>发现转载文章 {{ summary.repost_article_count }}</span><span>转载网站 {{ summary.repost_site_count }}</span><span>转载链接 {{ summary.repost_url_count }}</span></div><section class="trend"><h2>原创文章转载趋势</h2><el-empty v-if="!trend.length" description="当前筛选范围暂无原创文章" /><svg v-else viewBox="0 0 720 180" role="img" aria-label="原创文章转载趋势"><polyline :points="svgPoints" fill="none" stroke="#c90016" stroke-width="3" /><circle v-for="(point,index) in trend" :key="point.published_date" :cx="index * (680 / Math.max(1, trend.length - 1)) + 20" :cy="150 - (point.repost_url_count / Math.max(1, ...trend.map(item => item.repost_url_count))) * 120" r="4"><title>{{ point.published_date }}：{{ point.repost_url_count }} 条链接，{{ point.site_count }} 个网站，{{ point.article_count }} 篇原创</title></circle></svg><div class="trend-labels"><span v-for="point in trend" :key="point.published_date">{{ point.published_date }}</span></div></section><el-table :data="rows"><el-table-column prop="published_at" label="发布时间" min-width="150" /><el-table-column label="栏目"><template #default="scope">{{ scope.row.channel_name || scope.row.section_name || '—' }}</template></el-table-column><el-table-column prop="title" label="原创标题" min-width="300" /><el-table-column prop="repost_site_count" label="转载网站" /><el-table-column prop="repost_url_count" label="转载链接" /><el-table-column label="操作"><template #default="scope"><el-button link type="primary" @click="openDetail(scope.row)">查看详情</el-button></template></el-table-column></el-table></template>
      <template v-else><section class="export-panel"><h2>导出 Excel</h2><p>导出前会进行一次仅数据库刷新，并使用同一 <code>as_of</code> 快照生成文件；不会调用搜索服务。</p><dl><dt>当前文章</dt><dd>{{ summary.article_count }}</dd><dt>当前转载链接</dt><dd>{{ summary.repost_url_count }}</dd><dt>快照时间</dt><dd>{{ asOf || '—' }}</dd></dl><el-button type="success" :loading="exporting" @click="exportExcel">导出当前筛选结果</el-button></section></template>
      <el-pagination v-if="total" v-model:current-page="page" v-model:page-size="pageSize" :page-sizes="[20,50,100]" layout="total, sizes, prev, pager, next" :total="total" @current-change="load" @size-change="page = 1; load()" />
    </template>
    <el-drawer v-model="detailOpen" size="76%" :title="detail?.article.title || '监测详情'"><el-skeleton v-if="detailLoading" :rows="6" animated /><template v-else-if="detail"><h3>搜索候选与人工复核</h3><p class="note">仅保留标题相似度≥80%且发布时间晚于原创的候选。只有确认“外部转载”的链接会进入转载统计与 Excel；归入自有渠道的链接仅在“阅读量检测”中显示。</p><el-empty v-if="!detail.candidates.length" description="尚无已保存候选" /><el-table v-else :data="detail.candidates"><el-table-column prop="searched_at" label="搜索时间" min-width="160" /><el-table-column prop="search_phases" label="阶段" min-width="110"><template #default="scope">{{ scope.row.search_phases.join(' / ') }}</template></el-table-column><el-table-column prop="site_name" label="网站" min-width="130" /><el-table-column prop="title" label="候选标题" min-width="240" /><el-table-column label="URL" min-width="300"><template #default="scope"><a :href="scope.row.canonical_url" target="_blank" rel="noopener noreferrer">{{ scope.row.canonical_url }}</a></template></el-table-column><el-table-column prop="similarity_score" label="相似度" /><el-table-column label="复核状态" min-width="130"><template #default="scope">{{ relationLabel(scope.row.content_relation) }}</template></el-table-column><el-table-column prop="classification_reason" label="判定说明" min-width="180" /><el-table-column v-if="canOperate" label="人工复核" width="240"><template #default="scope"><el-button link type="primary" @click="reviewCandidate(scope.row, 'CONFIRM_REPOST')">确认转载</el-button><el-button link type="success" @click="reviewCandidate(scope.row, 'CONFIRM_OWNED')">归入阅读量</el-button><el-button link type="danger" @click="reviewCandidate(scope.row, 'EXCLUDE')">排除</el-button></template></el-table-column></el-table><h3>外部转载结果</h3><el-empty v-if="!detail.reposts.length" description="暂无已确认的外部转载记录" /><el-table v-else :data="detail.reposts"><el-table-column prop="site_name" label="网站" /><el-table-column prop="result_title" label="标题" min-width="260" /><el-table-column label="URL" min-width="320"><template #default="scope"><a :href="scope.row.canonical_url || scope.row.normalized_url" target="_blank" rel="noopener noreferrer">{{ scope.row.canonical_url || scope.row.normalized_url }}</a></template></el-table-column><el-table-column prop="availability_status" label="链接状态" /><el-table-column prop="first_found_at" label="首次发现" min-width="160" /></el-table><h3>搜索运行记录</h3><el-table :data="detail.runs"><el-table-column prop="created_at" label="时间" min-width="160" /><el-table-column prop="provider" label="搜索服务" /><el-table-column prop="exact_candidate_count" label="EXACT" /><el-table-column prop="broad_candidate_count" label="BROAD" /><el-table-column prop="merged_candidate_count" label="合并候选" /><el-table-column prop="matched_count" label="已确认/匹配" /><el-table-column prop="repost_count" label="外部转载" /><el-table-column prop="review_required_count" label="待复核" /><el-table-column prop="error_message" label="异常" min-width="180" /></el-table></template></el-drawer>
    <el-dialog v-model="reviewDialogOpen" :title="reviewDialogTitle()" width="460px" :close-on-click-modal="false">
      <p class="review-note">{{ reviewingCandidate?.title }}</p>
      <el-form label-position="top">
        <el-form-item v-if="reviewAction === 'CONFIRM_OWNED'" label="自有渠道" required>
          <el-select v-model="reviewOwnedChannelId" placeholder="请选择已启用自有渠道" style="width: 100%">
            <el-option v-for="channel in ownedChannels" :key="channel.id" :label="channel.name" :value="channel.id" />
          </el-select>
        </el-form-item>
        <el-form-item label="复核原因" required>
          <el-input v-model="reviewReason" type="textarea" :rows="3" maxlength="500" show-word-limit placeholder="例如：人工确认标题、来源与原创文章一致" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button :disabled="reviewSubmitting" @click="reviewDialogOpen = false">取消</el-button>
        <el-button type="primary" :loading="reviewSubmitting" @click="submitCandidateReview">确认</el-button>
      </template>
    </el-dialog>
  </section>
</template>

<style scoped>
.monitoring-panel{display:grid;gap:16px}.heading{display:flex;justify-content:space-between;align-items:start;gap:16px}.heading h1{margin:0}.heading p{margin:8px 0 0;color:#6b7280}.filters,.actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.filters .el-select{width:145px}.filters .title-filter{width:220px}.status-summary,.summary{display:flex;gap:12px;flex-wrap:wrap}.status-summary .el-card{min-width:135px}.status-summary strong{display:block;font-size:24px;margin-top:6px}.summary span{background:#f3f4f6;padding:8px 12px;border-radius:4px}.trend{border:1px solid #e5e7eb;padding:16px}.trend h2{margin-top:0}.trend svg{width:100%;max-height:220px}.trend circle{fill:#c90016}.trend-labels{display:flex;justify-content:space-between;gap:8px;font-size:12px;color:#6b7280;overflow:hidden}.export-panel{max-width:640px}.export-panel dl{display:grid;grid-template-columns:140px 1fr;gap:10px}.export-panel dt{color:#6b7280}.export-panel dd{margin:0}@media(max-width:900px){.filters .el-select,.filters .title-filter{width:100%}}
</style>
